GET http://localhost:8080/events

###
GET http://localhost:8080/events/1

###
GET http://localhost:8080/events/1/spots

###
POST http://localhost:8080/event/1/reserve
Content-Type: application/json

{
  "name": "A2"
}